apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: honkit-es
  name: honkit-es
  namespace: default
spec:
  replicas: 1
  serviceName: honkit-es
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
      app.kubernetes.io/instance: honkit-es
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch
        app.kubernetes.io/instance: honkit-es
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms2048M -Xmx2048M
            - name: discovery.type
              value: single-node
          image: ghcr.io/zoetrope/elasticsearch:7.9.3
          imagePullPolicy: IfNotPresent
          name: elasticsearch
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "2"
              memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: honkit-es
  name: honkit-es
  namespace: default
spec:
  ports:
    - port: 9200
      name: http
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: honkit-es
