apiVersion: website.zoetrope.github.io/v1beta1
kind: WebSite
metadata:
  name: gatsby-sample
  namespace: default
spec:
  buildImage: ghcr.io/zoetrope/node:16.13.2
  buildScript:
    configMap:
      name: build-scripts
      key: build-gatsby.sh
  repoURL: https://github.com/zoetrope/gatsby-sample.git
  branch: main
  extraResources:
    - configMap:
        name: httpproxy
        key: httpproxy.tmpl
