apiVersion: website.zoetrope.github.io/v1beta1
kind: WebSite
metadata:
  name: gatsby-sample
  namespace: default
spec:
  buildImage: ghcr.io/zoetrope/node:18.12.1
  buildScript:
    configMap:
      name: build-scripts
      key: build-gatsby.sh
  repoURL: https://github.com/gatsbyjs/gatsby-starter-default.git
  branch: master
  extraResources:
    - configMap:
        name: httpproxy
        key: httpproxy.tmpl
