apiVersion: website.zoetrope.github.io/v1beta1
kind: WebSite
metadata:
  name: honkit-sample
  namespace: default
spec:
  buildImage: ghcr.io/zoetrope/node:12.19.0
  buildScript:
    configMap:
      name: build-scripts
      key: build-honkit.sh
  repoURL: https://github.com/zoetrope/honkit-sample.git
  branch: main
  jobScript:
    configMap:
      name: job-scripts
      key: job-honkit.sh
  extraResources:
    - configMap:
        name: httpproxy
        key: httpproxy.tmpl
