apiVersion: website.zoetrope.github.io/v1beta1
kind: WebSite
metadata:
  name: honkit-sample
  namespace: default
spec:
  buildImage: ghcr.io/zoetrope/node:18.12.1
  buildScript:
    configMap:
      name: build-scripts
      key: build-honkit.sh
  repoURL: https://github.com/zoetrope/honkit-sample.git
  branch: main
  afterBuildScript:
    configMap:
      name: after-build-scripts
      key: after-build-honkit.sh
  extraResources:
    - configMap:
        name: httpproxy
        key: httpproxy.tmpl
