apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - elasticsearch.yaml
  - honkit.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: honkit-deploy-key
    files:
      - .ssh/id_rsa
      - .ssh/config
