apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - honkit.yaml
  - pvc.yaml
  - mkdocs.yaml
  - gatsby.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: mkdocs-deploy-key
    files:
      - .ssh/id_rsa
      - .ssh/config
