apiVersion: website.zoetrope.github.io/v1beta1
kind: WebSite
metadata:
  name: mkdocs-sample
  namespace: default
spec:
  buildImage: ghcr.io/zoetrope/python:3.8.5
  buildScript:
    configMap:
      name: build-scripts
      key: build-mkdocs.sh
  repoURL: git@github.com:zoetrope/mkdocs-sample.git
  branch: main
  deployKeySecretName: mkdocs-deploy-key
  extraResources:
    - configMap:
        name: httpproxy
        key: httpproxy.tmpl
