apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-home
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
