apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-website-operator-dev
product: kind
kubernetesVersion: v1.27.11 # renovate: kindest/node
registry: ctlptl-registry
