FROM ghcr.io/zoetrope/ubuntu:24.04

LABEL org.opencontainers.image.source https://github.com/zoetrope/website-operator

COPY ui/frontend/dist /dist
COPY website-operator-ui /

USER 10000:10000

ENTRYPOINT ["/website-operator-ui"]
