apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: website-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: website-operator-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - command:
            - /website-operator
          args:
            - --enable-leader-election
            - --repochecker-container-image=ghcr.io/zoetrope/repo-checker:dev
          image: ghcr.io/zoetrope/website-operator:dev
          name: manager
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 256Mi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      terminationGracePeriodSeconds: 10
