apiVersion: website.zoetrope.github.io/v1beta1
kind: WebSite
metadata:
  name: honkit-sample-es
  namespace: default
spec:
  buildImage: ghcr.io/zoetrope/node:22.16.0
  buildScript:
    configMap:
      name: build-scripts
      key: build-honkit.sh
  buildSecrets:
    - name: build-secret
      key: ELASTIC_HOST
  repoURL: https://github.com/zoetrope/honkit-sample.git
  afterBuildScript:
    configMap:
      name: after-build-scripts
      key: create-honkit-es-index.sh
  branch: main
  extraResources:
    - configMap:
        name: httpproxy
        key: httpproxy-es.tmpl
