apiVersion: website.zoetrope.github.io/v1beta1
kind: WebSite
metadata:
  name: honkit-sample-es
  namespace: default
spec:
  buildImage: ghcr.io/zoetrope/node:12.19.0
  buildScript:
    configMap:
      name: build-scripts
      key: build-honkit-es.sh
  buildSecretName: build-secret
  repoURL: https://github.com/zoetrope/honkit-sample.git
  branch: main
  extraResources:
    - configMap:
        name: httpproxy
        key: httpproxy-es.tmpl
