apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: website-operator-ui
  name: ui
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: website-operator-ui
  type: ClusterIP
