apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: system
  labels:
    app.kubernetes.io/name: ui
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui
    spec:
      containers:
        - command:
            - /ui
          image: ghcr.io/zoetrope/website-operator-ui:dev
          name: ui
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      terminationGracePeriodSeconds: 10
