# permissions for end users to view websites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: website-viewer-role
rules:
- apiGroups:
  - website.zoetrope.github.io
  resources:
  - websites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - website.zoetrope.github.io
  resources:
  - websites/status
  verbs:
  - get
