apiVersion: website.zoetrope.github.io/v1beta1
kind: WebSite
metadata:
  name: docusaurus-sample
  namespace: default
spec:
  buildImage: ghcr.io/zoetrope/node:22.16.0
  buildScript:
    rawData: |
        #!/bin/bash -ex
        cd $HOME
        rm -rf $REPO_NAME
        git clone $REPO_URL
        cd $REPO_NAME
        git checkout $REVISION
    
        npm install
        npm run build
    
        rm -rf $OUTPUT/*
        cp -r build/* $OUTPUT/
  repoURL: https://github.com/zoetrope/docusaurus-sample.git
  branch: main
  publicURL: http://localhost:9191
  nginxConf:
    rawData: |
      worker_processes  2;
      error_log  /dev/stderr warn;
      pid /var/log/nginx/nginx.pid;

      events {
          worker_connections  2048;
          multi_accept on;
      }

      http {
          access_log  /dev/stdout;
          include     mime.types;

          server {
              listen       8080;
              server_name  localhost;
              absolute_redirect off;

              location / {
                  root   /data/;
                  index  index.html index.htm;
              }
          }
      }
