apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "website-operator.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "website-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "website-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "website-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /website-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "website-operator.fullname" . }}-ui
  labels:
  {{- include "website-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: website-operator-ui
    {{- include "website-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: website-operator-ui
      {{- include "website-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --allow-cors=false
        command:
        - /website-operator-ui
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default
          .Chart.AppVersion }}
        name: ui
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
      terminationGracePeriodSeconds: 10
