apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "website-operator.fullname" . }}-manager-config
  labels:
  {{- include "website-operator.labels" . | nindent 4 }}
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    health:
      healthProbeBindAddress: {{ .Values.controller.config.health.healthProbeBindAddress
        | quote }}
    kind: ControllerManagerConfig
    leaderElection:
      leaderElect: {{ .Values.controller.config.leaderElection.leaderElect
        }}
      resourceName: {{ .Values.controller.config.leaderElection.resourceName
        | quote }}
    metrics:
      bindAddress: {{ .Values.controller.config.metrics.bindAddress
        | quote }}
