apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "website-operator.fullname" . }}-ui-role
  labels:
  {{- include "website-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - website.zoetrope.github.io
  resources:
  - websites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - website.zoetrope.github.io
  resources:
  - websites/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "website-operator.fullname" . }}-ui-rolebinding
  labels:
  {{- include "website-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "website-operator.fullname" . }}-ui-role'
subjects:
- kind: ServiceAccount
  name: default
  namespace: '{{ .Release.Namespace }}'