apiVersion: v1
kind: Service
metadata:
  name: {{ include "website-operator.fullname" . }}-ui
  labels:
  {{- include "website-operator-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
  {{- include "website-operator-ui.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ui.service.ports | toYaml | nindent 2 -}}
