apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: website-operator-system
resources:
  - ../default
patchesStrategicMerge:
  - manager.yaml
images:
  - name: ghcr.io/zoetrope/website-operator
    newTag: 0.0.2
