apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: website-operator-system
resources:
  - ../../../config/default
  - rbac.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: build-honkit
    files:
      - build-honkit.sh
      - build-honkit-es.sh
  - name: build-mkdocs
    files:
      - build-mkdocs.sh
  - name: httpproxy
    files:
      - httpproxy.tmpl
      - httpproxy-es.tmpl
