apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: website-operator-system
resources:
  - ../../../config/default
  - rbac.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: build-scripts
    files:
      - build-honkit.sh
      - build-mkdocs.sh
      - build-gatsby.sh
  - name: httpproxy
    files:
      - httpproxy.tmpl
      - httpproxy-es.tmpl
  - name: after-build-scripts
    files:
      - after-build-honkit.sh
      - create-honkit-es-index.sh
