apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          image: ghcr.io/cybozu-go/website-operator:dev-amd64
          args:
            - --repochecker-container-image=ghcr.io/cybozu-go/repo-checker:dev-amd64
