apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: {{.Name}}-es
  name: {{.Name}}-es
  namespace: {{.Namespace}}
spec:
  ports:
    - port: 9200
      name: http
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: {{.Name}}-es
