apiVersion: website.zoetrope.github.io/v1beta1
kind: WebSite
metadata:
  name: honkit-website
  namespace: default
spec:
  buildImage: ghcr.io/zoetrope/node:12.19.0
  buildScript:
    rawData: |-
      #!/bin/bash -ex
      cd $HOME
      git clone $REPO_URL
      cd $REPO_NAME
      git checkout $REVISION
      npm install && npm run build
      cp -r _book/* /data/
  repoURL: https://github.com/zoetrope/honkit-sample.git
  branch: main
