apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../config/default
  - honkit.yaml
secretGenerator:
  - name: honkit-deploy-key
    files:
      - .ssh/id_rsa
      - .ssh/config
